name: Update README
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-snake:
    name: Update this repo's snake with repository_owner
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./assets/snake.svg
            ./assets/snake-dark.svg?palette=github-dark
      - name: Push to GitHub
        uses: EndBug/add-and-commit@main
        with:
          branch: main
          message: ':rocket: Update'
  update-articles:
    name: Update this repo's README with repository_owner
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: Install dependencies
        run: npm ci

      - name: Run RSS Fetch Script
        run: npm run start

      - name: Push to GitHub
        uses: EndBug/add-and-commit@main
        with:
          branch: main
          message: 'Update readme with new articles'